import './ScriptStep.css'

export default function ScriptStep({ analysis }) {
  const vp = analysis?.video_proposal || {}
  const hook = vp.hook || ''
  const outline = vp.script_outline || []

  return (
    <div className="script-step">
      <div className="ss-header">
        <div className="ss-step-badge">STEP 1</div>
        <h3 className="ss-title">Script &amp; Hook</h3>
        <span className="ss-done-badge">✅ Generated by Claude</span>
      </div>

      <div className="ss-body">
        {hook && (
          <div className="ss-hook-block">
            <span className="ss-label">Opening Hook</span>
            <blockquote className="ss-hook">"{hook}"</blockquote>
          </div>
        )}

        {outline.length > 0 && (
          <div className="ss-outline-block">
            <span className="ss-label">Script Outline</span>
            <div className="ss-outline">
              {outline.map((item, i) => (
                <div key={i} className="ss-outline-row">
                  <span className="ss-timestamp">{item.timestamp}</span>
                  <span className="ss-action">{item.action}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="ss-note">
          The avatar in Step 2 will deliver a spoken version of this script.
          Background scenes in Step 3 will visually match this content direction.
        </p>
      </div>
    </div>
  )
}
